# Generated by Django 5.1.6 on 2025-04-13 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmodule', '0002_address_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='address',
        ),
        migrations.RemoveField(
            model_name='student',
            name='age',
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=300),
        ),
        migrations.AddField(
            model_name='student',
            name='card',
            field=models.OneToOneField(default=1000, on_delete=django.db.models.deletion.PROTECT, to='bookmodule.card'),
            preserve_default=False,
        ),
    ]
