# Generated by Django 5.1.6 on 2025-04-13 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmodule', '0003_card_remove_student_address_remove_student_age_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='card',
        ),
        migrations.DeleteModel(
            name='Card',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
