# Generated by Django 5.1.6 on 2025-04-27 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmodule', '0008_address2_student3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address2',
            name='street',
        ),
    ]
